services: 
  db:
    container_name: patscompare-db
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - patscompare-db-data:/var/lib/postgresql/data

  redis: 
    container_name: patscompare-redis 
    restart: unless-stopped
    image: redis:7 
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - patscompare-redis-data:/data

  minio:
    container_name: patscompare-minio
    restart: unless-stopped
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT1}:9000"
      - "${MINIO_PORT2}:9001"
    command: server /data
    volumes:
      - patscompare-minio-data:/data
  
  web:
    container_name: patscompare-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - ROLE=web
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ENDPOINT=${MINIO_HOST}:${MINIO_PORT1}
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - NEXT_PUBLIC_SOCKET_HOST=${NEXT_PUBLIC_SOCKET_HOST}
      - NEXT_PUBLIC_SOCKET_PORT=${NEXT_PUBLIC_SOCKET_PORT}
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./env:/opt/patscompare/.env
      - ./data:/opt/patscompare/data
    depends_on:
      - db
      - redis
      - minio

  socket:
    container_name: patscompare-socket
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.socket
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
      - SOCKET_PORT=${NEXT_PUBLIC_SOCKET_PORT}
      - SOCKET_LOG_LEVEL=${SOCKET_LOG_LEVEL}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    ports:
      - "${NEXT_PUBLIC_SOCKET_PORT}:5001"
    volumes:
      - ./env:/opt/patscompare/.env
    depends_on:
      - db
      - redis

  worker:
    container_name: patscompare-worker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ROLE=worker
      - WORKER_ID=1
      - WORKER_CONCURRENCY=1
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
      - WORKER_LOG_LEVEL=${WORKER_LOG_LEVEL}
      - MINIO_ENDPOINT=${MINIO_HOST}:${MINIO_PORT1}
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    volumes:
      - ./env:/opt/patscompare/.env
      - ./data:/opt/patscompare/data
    depends_on:
      - db
      - redis
      - minio

volumes:
  patscompare-db-data:
  patscompare-redis-data:
  patscompare-minio-data: