#TODO Ajustar para executar o servidor web  
FROM node:20-bullseye-slim

EXPOSE 3000

ENV ROLE=server

ENV NODE_ENV=production

WORKDIR /opt/patscompare

COPY entrypoint.sh start.sh package.json package-lock.json ./
COPY server ./server

RUN chmod +x ./entrypoint.sh ./start.sh

RUN npm ci --production

# build do Next já pronto, gerado no WSL
COPY .next ./.next
COPY public ./public
COPY server ./server

ENTRYPOINT ["/opt/patscompare/entrypoint.sh"]